=== javiercuenca/mondragon.github.io/tabla_resultados/resultados.xsd
<?xml version="1.0" encoding="UTF-8"?> 
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Página_web"> 
		<xs:complexType> 
			<xs:sequence>
				<xs:element name="Cliente"> 
					<xs:complexType> 
						<xs:sequence>
							<xs:element name="Usuario"> 
								<xs:complexType> 
									<xs:sequence>
										<xs:element name="Nombre">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Médico">
														<xs:simpleType> 
															<xs:restriction base="xs:string">
																<xs:pattern value="Dr.|Dra."/> 
															</xs:restriction> 
														</xs:simpleType>
													</xs:element>
													<xs:element name="Apellidos">
														<xs:simpleType> 
																<xs:restriction base="xs:string">
																	<xs:pattern value="[A-Z][a-z]+ [A-Z][a-z]+"/> 
																</xs:restriction> 
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="Diagnóstico" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="ID_paciente">
														<xs:simpleType> 
															<xs:restriction base="xs:string">
																<xs:pattern value="[0-9]{8}"/> 
															</xs:restriction> 
														</xs:simpleType>
													</xs:element>
													<xs:element name="Fecha_del_diagnóstico" type="xs:date"/>
													<xs:element name="Resultado_de_diagnóstico">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="Resultado">
																	<xs:simpleType> 
																			<xs:restriction base="xs:string">
																				<xs:pattern value="Con tumor|Sin tumor|Sin resultado"/> 
																			</xs:restriction> 
																	</xs:simpleType>
																</xs:element>
																<xs:element name="Gráfico">
																	<xs:complexType>
																		<xs:attribute name="imagen" type="xs:string"/>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>													
												</xs:sequence>
												<xs:attribute name="id" type="xs:integer" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="id" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="nombre" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== javiercuenca/mondragon.github.io/tabla_resultados/resultados.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="resultados.xslt"?>
<!--<!DOCTYPE Página_web SYSTEM "resultados.dtd">-->

<Página_web xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="resultados.xsd">
	<Cliente nombre='Osakidetza'>
		<Usuario id='4785A'>
			<Nombre>
				<Médico>Dr.</Médico>
				<Apellidos>Martínez Valero</Apellidos>
			</Nombre>
			
			<Diagnóstico id='01'>
				<ID_paciente>12049875</ID_paciente>
				<Fecha_del_diagnóstico>2021-05-24</Fecha_del_diagnóstico>
				<Resultado_de_diagnóstico>
					<Resultado>Con tumor</Resultado>
					<Gráfico imagen="01_con_tumor.jpg"/>
				</Resultado_de_diagnóstico>
			</Diagnóstico>
			
			<Diagnóstico id='02'>
				<ID_paciente>13564978</ID_paciente>
				<Fecha_del_diagnóstico>2021-03-05</Fecha_del_diagnóstico>
				<Resultado_de_diagnóstico>
					<Resultado>Sin tumor</Resultado>
					<Gráfico imagen="02_sin_tumor.jpeg"/>
				</Resultado_de_diagnóstico>
			</Diagnóstico>

			<Diagnóstico id='03'>
				<ID_paciente>65234896</ID_paciente>
				<Fecha_del_diagnóstico>2022-06-09</Fecha_del_diagnóstico>
				<Resultado_de_diagnóstico>
					<Resultado>No concluyente</Resultado>
					<Gráfico imagen="03_no_concluyente.jpeg"/>
				</Resultado_de_diagnóstico>
			</Diagnóstico>
		</Usuario>
	</Cliente>
</Página_web>
